version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: hgfdhg
      MONGO_INITDB_ROOT_PASSWORD: ghddfghdfgd
    volumes:
    - ${PWD}/database:/data/db
  api-ob2020:
    build:
      dockerfile: Dockerfile.API
      context: ./
    # image: bostrot/ob2020-api #debug
    volumes:
    - ./:/src
    restart: unless-stopped
  nginx-botspace:
    image: nginx:1.13-alpine
    ports:
    - "4006:443"
    volumes:
    - ./site.conf:/etc/nginx/conf.d/default.conf
    - ./ssl:/ssl
    restart: unless-stopped
  mongo-express-ob2020:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hgfdhg
      ME_CONFIG_MONGODB_ADMINPASSWORD: ghddfghdfgd
  #ob2020-yake:
  #  image: liaad/yake-server:latest
  #  restart: unless-stopped

